project:
  type: website

website:
  title: "Indicador de Desempeño Económico"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Acerca de

format:
  html:
    theme: cosmo
    lang: es
    css: styles.css
    toc: true



